credentials:
  usernames:
    nuruddin:
      email: nuruddindev@gmail.com
      name: Admin
      password: '$2b$12$Gsr7t0NL04OCuS4k3YfMru0zZTMOR2eEbwNkGsKUEnRjopyf01xUK' # To be replaced with hashed password
      # '$2b$12$q2Nu6E0ZiukCjBnKYPO7K.3j.KyfJ9KpVsN3S16Y5CB/S90iR2s6m'
    harifit:
      email: nilakusuma783@gmail.com
      name: Hari Fitrianto
      password: '$2b$12$.LZSNjI.OaEKwLcDlnVFyO6RdPDNASH431jrnFHWpaM8BxetGSfT6' # To be replaced with hashed password
      #'$2b$12$WQok74nLk7/7j6Hz8PzLNuECazLrH3hYR7CD6xQ77/lM4f/Lk.cS6'
cookie:
  expiry_days: 30
  key: picalogin # Must be string
  name: picalogs
preauthorized:
  emails:
  - picstare@gmail.com